### DISCUSSION TITLE
主题配置问题

### DISCUSSION THREAD

**Discussion by MuyangLarry** [liuyib/hexo-theme-stun#251] [Q&A（反馈问题、提问、报告 Bug 等）] [answered]
正确添加了搜索功能，搜索框的位置会跳到其他地方；
正确添加了网页上方的背景图片，但是没有效果；
正确将作者信息侧栏从右侧更换至左侧，但是没有效果。
这些问题在本地用 "hexo s" 打开的预览主题的网页中是完全不存在的。
网址：https://muyanglarry.github.io/

**Comment by BestJarvan** [comment, marked as answer]
1. 没遇到过
2. 背景没显示可能是根_config.yml的root配置不对，参考下面的
```yml
url: https://example.com/
root: /
```
其次发布之前也可以先运行`hexo g`生成public文件之后，通过http-serve服务启动此文件查看下发布后的效果，方便调试
3. 
```yml
sidebar:
  enable: true
  position: left
  offsetTop: 20px
  horizon_line: false
```
