### DISCUSSION TITLE
添加特效不起作用

### DISCUSSION THREAD

**Discussion by gjssss** [liuyib/hexo-theme-stun#253] [Q&A（反馈问题、提问、报告 Bug 等）]
根据[文档](https://theme-stun.github.io/docs/zh-CN/advanced/third-part.html#%E7%89%B9%E6%95%88)所说修改配置文件
```yml
  canvas_nest:
    enable: true
    color: "0,0,255"
    opacity: 0.6
    count: 99
    zIndex: -1
```

却没有得到任何的效果，请问应该如何配置
