### ISSUE TITLE
使用Gitalk但无法评论,并提示"Error: Not Found."

### ISSUE THREAD

**Issue by HYSWZW** [liuyib/hexo-theme-stun#142]
## 我想创建一个新的 issue

- [x] 是的，我已经阅读了 [常见问题](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md)。
- [x] 是的，我搜索并阅读了 [Issues 列表](https://github.com/liuyib/hexo-theme-stun/issues)（包括关闭的），但是没有帮助到我。
- [x] 是的，我是第一次使用 Stun 主题。
- [x] 是的，我之前用过 Stun 主题，并且可以正常运行。但是当我启用Gitalk开启评论后,无法进行评论,页面一直显示"Error: Not Found"。
- [] 是的，我使用了 [平滑升级](https://theme-stun.github.io/docs/zh-CN/advanced/advanced.html#%E5%B9%B3%E6%BB%91%E5%8D%87%E7%BA%A7) 的特性，并且阅读了其文档。

## 环境信息

**Stun 版本：** 1.7.0

**Hexo 版本：4.2.0

**平台信息:** win10 专业版

**浏览器信息:** 

**Node.js 和 NPM 版本：** 
PS D:\hexo> node -v
v12.16.1
PS D:\hexo> npm -v
6.13.4

**NPM 依赖信息：**
hexo-site@0.0.0 D:\hexo
+-- hexo@4.2.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-search@2.4.0
+-- hexo-generator-tag@1.0.0
+-- hexo-render-pug@2.1.4
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
`-- hexo-wordcount@6.0.1

**Hexo 配置信息：**

<details>
<summary>查看代码 ...</summary>

```yml

```
</details>

**Stun 配置信息：**

<details>
<summary>查看代码 ...</summary>

```yml
gitalk:
  enable: true
  # Github username.
  owner: HYSWZW
  # Github repository.
  repo: https://github.com/HYSWZW/Comment
  # Github Application Client ID.
  client_id: b3620a1***1cee97eb
  # Github Application Client Secret.
  client_secret: 77aa4a3c2f297df767***9775d164d300b0cfb
  # GitHub repo owner and collaborators, only these guys can initialize github issues.
  admin: HYSWZW
  # Facebook-like distraction free mode.
  distraction_free_mode: true
  # Gitalk's display language depends on user's browser or system environment.
  # If you want everyone visiting your site to see a uniform language, you can set a force language value.
  # Optional values: en | zh-CN | es-ES | fr | ru | zh-TW
  language: zh-CN
```
</details>

## 重现步骤

1. xxx
2. xxx
3. xxx

## 其他信息
![图片](https://user-images.githubusercontent.com/18552371/102690529-fde64980-4240-11eb-8a5c-43eec48a95a3.png)

---
