### ISSUE TITLE
KaTex渲染数学公式出现问题

### ISSUE THREAD

**Issue by kangyachengii** [liuyib/hexo-theme-stun#165]
## 我想创建一个新的 issue

- [x] 是的，我已经阅读了 [常见问题](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md)。
- [x] 是的，我搜索并阅读了 [Issues 列表](https://github.com/liuyib/hexo-theme-stun/issues)（包括关闭的），但是没有帮助到我。
- [x] 是的，我是第一次使用 Stun 主题。
- [ ] 是的，我之前用过 Stun 主题，并且可以正常运行。但是当我做了一些更改后，主题就无法正常运行了。
- [ ] 是的，我使用了 [平滑升级](https://theme-stun.github.io/docs/zh-CN/advanced/advanced.html#%E5%B9%B3%E6%BB%91%E5%8D%87%E7%BA%A7) 的特性，并且阅读了其文档。

## 环境信息

**Stun 版本：** v2.6.2

**Hexo 版本：** v5.3.0

**平台信息:** Windows_NT 10.0.19042 win32 x64

**浏览器信息:** Chrome 90, Firefox 86

**Node.js 和 NPM 版本：**

```
$ node -v && npm -v
v12.20.2
6.14.11
```

**NPM 依赖信息：**

```
+-- hexo@5.3.0
+-- hexo-deployer-git@3.0.0
+-- hexo-filter-github-emojis@3.0.4
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-search@2.4.1
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-markdown-it-plus@1.0.4
+-- hexo-renderer-pug@1.0.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@2.0.0
+-- hexo-submit-urls-to-search-engine@2.0.0
+-- hexo-theme-landscape@0.0.3
+-- hexo-wordcount@6.0.1
`-- highlight.js@10.6.0
```

## 实际行为
作者您好，我非常喜欢Stun主题，感谢您的辛苦创作！

在最近的使用中我遇到了一个问题，发现渲染器会错误渲染数学公式，在不同浏览器中显示效果都不一样。

在Chrome中，效果是这样的：
![image](https://user-images.githubusercontent.com/21194470/108153613-77ea6000-7116-11eb-8fc7-3adca2e4a131.png)

而在Firefox中，效果是这样的：
![image](https://user-images.githubusercontent.com/21194470/108153662-8f294d80-7116-11eb-8d83-810f4a55b167.png)

无论如何，数学公式都会出现两次。渲染器使用的是stun推荐的 hexo-renderer-markdown-it-plus ，主题_config.yml中的部分配置如下：
```
minivaline:
  enable: false
  appId: # Your leancloud application appid
  appKey: # Your leancloud application appkey
  placeholder: Write a Comment # Comment box placeholder
  adminEmailMd5: # The MD5 of Admin Email to show Admin Flag.
  math: false # Support MathJax.
  md: true # Support Markdown.

math:
  enable: true
  # If true, this function will be enabled on every page.
  # If false, this function will be enabled only if the page where `math: true` is set in `Front-matter`.
  per_page: false
  # ! -------------------------------------------------------------------------------
  # ! Please see the documentation before using. See:
  # ! https://theme-stun.github.io/docs/zh-CN/advanced/third-part.html#mathjax
  # ! -------------------------------------------------------------------------------
  # Optional values: mathjax | katex
  engine: katex
```

我主要是在这两项配置中尝试解决问题，但是毫无作用。
这个问题让我很头疼，特来寻求大家的帮助，感谢！
