### ISSUE TITLE
Unable to initial search

### ISSUE THREAD

**Issue by evalexp** [liuyib/hexo-theme-stun#236]
The local search could not be initial on my website, it works on local service.

When I click search, nothing happend.

I think this may be a bug.

By the way, I use a windows PC to preview and write the blog, but I use linux docker container to build my blog, I could not ensure that if this cause this problem.

The Docker image is node:16-alpine, and the build command as :
```bash
  | - npm install hexo -g
  | - npm install
  | - hexo g
  | - tar -czvf publish.tar.gz -C public .
```
And my blog is behind Cloudflare, hope could solve this problem soon.

**Comment by evalexp** [comment]
OK, I debug the public static website myself, and I find that the event DOMContentLoaded handler was registered after the event. 

And because of this, the handler function was not called as expected.

I migrate the handler call-time from "window.DOMContentLoaded" to "window.load", and that works for my website.

And here's the fix script, if someone met the same problem as me, the script might work:

```javascript
// fix-search.js
const fs = require("fs");

const file_name = __dirname + "/public/index.html";
const origin_event_name = "DOMContentLoaded";
const new_event_name = "load";

if (fs.existsSync(file_name)) {
  let content = fs.readFileSync(file_name).toString();
  content = content.replace(origin_event_name, new_event_name);
  fs.writeFileSync(file_name, content);
  console.log(
    `Your search engine initial time has been changed from "window.${origin_event_name}" to "window.${new_event_name}"`
  );
} else {
  console.error("Please generate your blog static file fiest.");
}
```

But please pay attention, this script would NOT execute automatically, so you build step might consider to add a command:

```bash
node fix-search.js
```

If you also use drone to automatically build, you can refer to my profile:
```yml
steps:
// some steps before
  - name: build
    image: node:16-alpine
    commands:
      - npm install hexo -g
      - npm install
      - hexo g
      - node fix-search.js
      - tar -czvf publish.tar.gz -C public .
// some steps after
```

**Comment by evalexp** [comment]
OK, I debug the public static website myself, and I find that the event DOMContentLoaded handler was registered after the event. 

And because of this, the handler function was not called as expected.

I migrate the handler call-time from "window.DOMContentLoaded" to "window.load", and that works for my website.

And here's the fix script, if someone met the same problem as me, the script might work:

```javascript
// fix-search.js
const fs = require("fs");

const file_name = __dirname + "/public/index.html";
const origin_event_name = "DOMContentLoaded";
const new_event_name = "load";

if (fs.existsSync(file_name)) {
  let content = fs.readFileSync(file_name).toString();
  content = content.replace(origin_event_name, new_event_name);
  fs.writeFileSync(file_name, content);
  console.log(
    `Your search engine initial time has been changed from "window.${origin_event_name}" to "window.${new_event_name}"`
  );
} else {
  console.error("Please generate your blog static file fiest.");
}
```

But please pay attention, this script would NOT execute automatically, so you build step might consider to add a command:

```bash
node fix-search.js
```

If you also use drone to automatically build, you can refer to my profile:
```yml
steps:
// some steps before
  - name: build
    image: node:16-alpine
    commands:
      - npm install hexo -g
      - npm install
      - hexo g
      - node fix-search.js
      - tar -czvf publish.tar.gz -C public .
// some steps after
```
