### ISSUE TITLE
希望 canvas_nest 能够支持 onmobile 参数

### ISSUE THREAD

**Issue by BYJRK** [liuyib/hexo-theme-stun#238]
比如 NexT 主题，就支持对 canvas_nest 提供一个额外的 onmobile 参数，用来控制这个背景动效是否在移动端显示

```yaml
canvas_nest:
  enable: true
  onmobile: true # display on mobile or not
  color: '0,0,255' # RGB values, use ',' to separate
  opacity: 0.5 # the opacity of line: 0~1
  zIndex: -1 # z-index property of the background
  count: 99 # the number of lines
```

我试了一下，目前 Stun 是不支持这个功能的
