### ISSUE TITLE
无法使用特效

### ISSUE THREAD

**Issue by gjssss** [liuyib/hexo-theme-stun#252]
# 无法使用特效
根据[文档](https://theme-stun.github.io/docs/zh-CN/advanced/third-part.html#%E7%89%B9%E6%95%88)所说修改配置文件
```yml
  canvas_nest:
    enable: true
    color: "0,0,255"
    opacity: 0.6
    count: 99
    zIndex: -1
```
却没有得到任何的效果，请问应该如何配置
