### ISSUE TITLE
应用stun后index页直接显示html标签

### ISSUE THREAD

**Issue by Megumism** [liuyib/hexo-theme-stun#32]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 
1.7.0 ? maybe，我新clone的

**Hexo Version:** 
hexo: 4.2.0
hexo-cli: 3.1.0

**Platform:**
os: Windows_NT 10.0.18362 win32 x64

**Browser:** 
Chrome

## Expected behaviour 
预期就是好好显示啊……

## Actual behaviour 

页面截图如下：
![3KtQL8.png](https://s2.ax1x.com/2020/02/21/3KtQL8.png)

原文章如下：
![3KtwLT.png](https://s2.ax1x.com/2020/02/21/3KtwLT.png)

## Steps to reproduce the behaviour 

1. hexo init 一个新的文件夹，下载hexo-deployer-git@2.1.0
2. 按照文档中的shell指令下载stun，下载NexT
3. 写一点md，预设的landscape正常，将theme调为NexT也正常
4. 调为stun就会出现上面的情况

## Feature Request 

其实我有考虑直接不理stun投向NexT，但是我真的觉得stun挺好看的，很戳我的审美，所以还是很希望解决问题，早日应用！

---

修好了就给Star！然后用英文重写一次issue方便国际友人！

**Comment by kinglyl** [comment]
修好了就给Star！修好了就没必要重写issue了吧？

**Comment by liuyib** [comment]
@Megumism 麻烦提供下你的 hexo 根目录下的 _config.yml 和 package.json 文件的内容。

**Comment by Megumism** [comment]
_config.yml:
```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 社蕙主义
subtitle: "春社野蕙，生生不息"
description: "社蕙先生在互联网上的居所"
keywords:
author: 社蕙
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false #edited
  line_number: true #edited
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:Megumism/blog.git
  branch: master
```

package.json:
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-generator-tag": "^1.0.0",
    "hexo-render-pug": "^2.1.4",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}
```
