### ISSUE TITLE
footer设置图片背景就不显示了，pug里面也没见有键值配对bg_image

### ISSUE THREAD

**Issue by impressionyang** [liuyib/hexo-theme-stun#43]
## I want to create a new issue 

- [ok] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [ok] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [ok] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [ok] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** v1.7.0

**Hexo Version:**  v4.2.0

**Platform:** Arch Linux

**Browser:** Chrome

## Expected behaviour 

**能够在显示footer背景的同时显示页脚信息**

- 正常页脚显示信息

![](https://impressionyang.gitee.io/imgbed/img/trouble/2020-03-28_14-41.png)

## Actual behaviour 

**什么都没有显示**

- 实际显示

![](https://impressionyang.gitee.io/imgbed/img/trouble/2020-03-28_14-42.png)

## Steps to reproduce the behaviour 

设置

```yml
footer:
  # Background image in the footer.
  bg_image:
    enable: true
    # In theme directory (source/images): /images/avatar.png
    # In site directory (source/uploads): /uploads/avatar.png
    # You can also use a link of image.
    url: /images/wallpaper/d_starts.svg
  # Mask effect of the background image.
```

**我使用的页脚背景图**

![](https://impressionyang.gitee.io/imgbed/img/trouble/d_starts.svg)

## Feature Request 

---
