### ISSUE TITLE
mathjax配置不成功，不进行渲染

### ISSUE THREAD

**Issue by poorpool** [liuyib/hexo-theme-stun#6]
## Stun Information

**Stun Version:** 
1.2.2

**Platform:** 
Windows 10

**Browser:** 
Firefox
## Expected behaviour 
在进行了相关的配置之后成功加载数学公式。

## Actual behaviour 
在进行了相关的配置之后未成功加载数学公式。

这是我的[示例网址](https://yxchen.net/2019/08/18/hello-world/)

可以看到并没有进行渲染。

这是`stun.yml`
```yml
math:
  enable: true

  # Only the page which has `math: true` in Front-matter will render.
  # If true, it will load mathjax / katex srcipt EVERY PAGE.
  per_page: true

  engine: mathjax

  # See: https://github.com/mathjax/MathJax/
  # hexo-renderer-pandoc (or hexo-renderer-kramed) needed to full MathJax support.
  mathjax:
    cdn: https://cdn.jsdelivr.net/npm/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML

    # See: https://mhchem.github.io/MathJax-mhchem/
    mhchem:
      enable: false
      mhchem_js: https://cdn.jsdelivr.net/npm/mathjax-mhchem@3.3.2/mhchem.min.js
  
```

这是`hello-world.md`
```markdown
---
title: Hello World
math: true
---

$a+b$


\[ a+b \]
```

![捕获.JPG](https://i.loli.net/2019/08/18/Vwhu9XUxmF5nglC.jpg)

---
