### ISSUE TITLE
The Sharing buttons below each article are losing

### ISSUE THREAD

**Issue by Motongxue** [liuyib/hexo-theme-stun#70]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 2.0.0-rc.0 (2020-03-31)

**Hexo Version:** downloaded on 2020-05-01(Maybe the lasted version)

**Platform:**  Windows 10

**Browser:** Chrome

## Expected behaviour 
Every sharing image don't show up. 
![](http://q9w6aimkr.bkt.clouddn.com/20200516160611.png)

## Actual behaviour 

The layout._partials.widgets.share.pug doesn't show up in expected .
And the stun's` _config.yml` has been setted in the rigth way.
```yml
# The widget of post.
post_widget:
  # Whether to show tags at the bottom of post.
  tags: true
  # Whether to show "------ END ------" at the bottom of post.
  end_text:
    enable: true
    # Whether to show a horizon line before "------ END ------".
    horizon_line: false
  # Article sharing
  share:
    enable: true
    # The text displayed before the share button.
    label: "Share to: "
    # Optional values: qzone | qq | weibo | wechat | douban | linkedin | facebook | twitter | google
    target: qzone, qq, weibo, wechat, douban, linkedin, facebook, twitter, google
```

## Feature Request 
Would you help to solve this problem ? It has  troubling me for few days. I even also try to read to source code and change the stun.layout._partials_widgets.share.pug. The details as follow.
```pug
if true
  div.post-share
    if true
      div.social-share(data-sites=`${socialShare.target}`)
        = socialShareLabel
```
But nothing happen. 
My blog site : motongxue.gitee.io
Could you please help for me ? Thank  you！

---
