### ISSUE TITLE
添加文字链接

### ISSUE THREAD

**Issue by chenyixing97** [liuyib/hexo-theme-stun#83]
footer添加文字链接应该怎么做？

**Comment by liuyib** [comment]
@chenyixing97
在配置文件里，查找：

```yaml
footer:
  custom:
    enable: true
    text: <a href="https://example.com">text</a>
```

设置其中的 `text` 字段（支持 html 语法）就行了
